### ISSUE TITLE
Fix Travis builds

### ISSUE THREAD

**Issue by XVilka** [mirage/ocaml-cstruct#209]
```
 ---> Running in 2510f340c950
[NOTE] travis-opam is not installed.
Nothing to do.
 ---> ea0249222a44
Removing intermediate container 2510f340c950
Step 6/13 : RUN opam switch 4.05.0
 ---> Running in aa291b251d25
[ERROR] No switch 4.05.0 is currently installed. Did you mean 'opam switch create 4.05.0'?
        Installed switches are:
          - 4.07
          - 4.06
          - 4.05
          - 4.04
          - 4.03
The command '/bin/sh -c opam switch 4.05.0' returned a non-zero code: 5
The command "bash -ex ./.travis-docker.sh" exited with 5.
```

**Comment by XVilka** [comment]
@samoht any ideas on how to fix this one? It would be nice to fix this before proceeding with other PRs or more patches.

**Comment by samoht** [comment]
The CI scripts have changed recently to switch to opam2 (which understands `opam switch 4.05.0` to "switch to the *existing* switch called 4.05.0) and to use built-in switches instead of having to rebuilt each compiler everytime -- these are now named `4.03`, 4.04`, ... 

So the fill fix for this is #211.

**Comment by XVilka** [comment]
I wonder why error `- ounit.2.0.8: Curl failed` appears for those Debian templates

**Comment by samoht** [comment]
I've pushed a patch to remove ounit. That should help with that error.
